// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 15.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TinyFxVSIX.Commands.OrmGen.Templates.MySqlClient
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using TinyFx.Data.MySqlClient;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewEOT.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class MySqlViewEOT : MySqlTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("/// <summary>\r\n/// ");
            
            #line 8 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassComment(CurrentView)));
            
            #line default
            #line hidden
            this.Write("\r\n/// 【视图 ");
            
            #line 9 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CurrentView.ViewName));
            
            #line default
            #line hidden
            this.Write(" 的实体类】\r\n/// </summary>\r\n[Serializable]\r\npublic class ");
            
            #line 12 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write(" : IRowMapper<");
            
            #line 12 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write(">\r\n{\r\n\t#region 所有字段\r\n");
            
            #line 15 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewEOT.tt"
 foreach (var column in CurrentView.Columns) {  
		string propertyName = column.OrmPropertyName;

            
            #line default
            #line hidden
            this.Write("\t/// <summary>\r\n\t/// ");
            
            #line 19 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PropertyComment(column)));
            
            #line default
            #line hidden
            this.Write("\r\n\t/// 【");
            
            #line 20 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.OrmColumnTypeString));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 20 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.EngineTypeStringFull));
            
            #line default
            #line hidden
            this.Write("】\r\n\t/// </summary>\r\n\tpublic ");
            
            #line 22 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.DotNetTypeString));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 22 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 23 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewEOT.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t#endregion // 所有列\r\n\r\n\t#region 实体映射\r\n\t\r\n\t/// <summary>\r\n\t/// 将IDataReader映射成实体对象\r" +
                    "\n\t/// </summary>\r\n\t/// <param name = \"reader\">只进结果集流</param>\r\n\t/// <return>实体对象<" +
                    "/return>\r\n\tpublic ");
            
            #line 33 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write(" MapRow(IDataReader reader)\r\n\t{\r\n\t\treturn MapDataReader(reader);\r\n\t}\r\n\t\r\n\t/// <su" +
                    "mmary>\r\n\t/// 将IDataReader映射成实体对象\r\n\t/// </summary>\r\n\t/// <param name = \"reader\">只" +
                    "进结果集流</param>\r\n\t/// <return>实体对象</return>\r\n\tpublic static ");
            
            #line 43 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write(" MapDataReader(IDataReader reader)\r\n\t{\r\n\t    ");
            
            #line 45 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write(" ret = new ");
            
            #line 45 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write("();\r\n");
            
            #line 46 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewEOT.tt"
 foreach (var column in CurrentView.Columns) {
		string propertyName = column.OrmPropertyName;

            
            #line default
            #line hidden
            this.Write("\t\tret.");
            
            #line 49 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write(" = reader.");
            
            #line 49 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.OrmReaderMethodName));
            
            #line default
            #line hidden
            this.Write("(\"");
            
            #line 49 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.ColumnName));
            
            #line default
            #line hidden
            this.Write("\");\r\n");
            
            #line 50 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewEOT.tt"
	} 
            
            #line default
            #line hidden
            this.Write("\t    return ret;\r\n\t}\r\n\t\r\n\t#endregion\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
