// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 15.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TinyFxVSIX.Commands.OrmGen.Templates.MySqlClient
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using TinyFx.Data.MySqlClient;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class MySqlTableEOT : MySqlTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("/// <summary>\r\n/// ");
            
            #line 8 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassComment(CurrentTable)));
            
            #line default
            #line hidden
            this.Write("\r\n/// 【表 ");
            
            #line 9 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CurrentTable.TableName));
            
            #line default
            #line hidden
            this.Write(" 的实体类】\r\n/// </summary>\r\n[Serializable]\r\npublic class ");
            
            #line 12 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write(" : IRowMapper<");
            
            #line 12 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write(">\r\n{\r\n\t/// <summary>\r\n\t/// 构造函数 \r\n\t/// </summary>\r\n\tpublic ");
            
            #line 17 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write("()\r\n\t{\r\n");
            
            #line 19 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
 foreach (var item in CurrentTable.Columns) {
		if (item.HasDefaultValue) {
			string value = item.OrmDefaultValueString;
			if (!string.IsNullOrEmpty(value)) { 
            
            #line default
            #line hidden
            this.Write("\t\tthis.");
            
            #line 23 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.OrmPropertyName));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 23 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(value));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 24 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
 
			}
		}
	} 
            
            #line default
            #line hidden
            this.Write("\t}\r\n\r\n\t#region 主键原始值 & 主键集合\r\n");
            
            #line 31 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
 
	// 主键原始值****************************************************************************************
if (CurrentTable.HasPrimaryKey){ 
            
            #line default
            #line hidden
            this.Write("    \r\n\t/// <summary>\r\n\t/// 当前对象是否保存原始主键值，当修改了主键值时为 true\r\n\t/// </summary>\r\n\tpublic" +
                    " bool HasOriginal { get; protected set; }\r\n");
            
            #line 39 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
		foreach (var column in CurrentTable.PrimaryKey.Columns)
		{
			string propertyName = column.OrmPropertyName;

            
            #line default
            #line hidden
            this.Write("\tprotected ");
            
            #line 43 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.DotNetTypeString));
            
            #line default
            #line hidden
            this.Write(" _original");
            
            #line 43 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write(";\r\n\t/// <summary>\r\n\t/// 【数据库中的原始主键 ");
            
            #line 45 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.ColumnName));
            
            #line default
            #line hidden
            this.Write(" 值的副本，用于主键值更新】\r\n\t/// </summary>\r\n\tpublic ");
            
            #line 47 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.DotNetTypeString));
            
            #line default
            #line hidden
            this.Write(" Original");
            
            #line 47 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t\tget { return _original");
            
            #line 49 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("; }\r\n\t\tset { HasOriginal = true; _original");
            
            #line 50 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write(" = value; }\r\n\t}\r\n");
            
            #line 52 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
		} 
            
            #line default
            #line hidden
            
            #line 53 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
	} 
            
            #line default
            #line hidden
            this.Write("    /// <summary>\r\n    /// 获取主键集合。key: 数据库字段名称, value: 主键值\r\n    /// </summary>\r\n " +
                    "   /// <returns></returns>\r\n    public Dictionary<string, object> GetPrimaryKeys" +
                    "()\r\n    {\r\n");
            
            #line 60 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
if (CurrentTable.HasPrimaryKey){ 
            
            #line default
            #line hidden
            this.Write("        return new Dictionary<string, object>() {");
            
            #line 61 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
foreach (var column in CurrentTable.PrimaryKey.Columns) {
            
            #line default
            #line hidden
            this.Write(" { \"");
            
            #line 61 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.OrmPropertyName));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 61 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.OrmPropertyName));
            
            #line default
            #line hidden
            this.Write(" }, ");
            
            #line 61 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
} 
            
            #line default
            #line hidden
            this.Write("};\r\n");
            
            #line 62 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\t\treturn null;\r\n");
            
            #line 64 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
 } 
            
            #line default
            #line hidden
            this.Write("    }\r\n    /// <summary>\r\n    /// 获取主键集合JSON格式\r\n    /// </summary>\r\n    /// <retu" +
                    "rns></returns>\r\n    public string GetPrimaryKeysJson() => SerializerUtil.Seriali" +
                    "zeJson(GetPrimaryKeys());\r\n\t#endregion // 主键原始值\r\n\r\n\t#region 所有字段\r\n");
            
            #line 74 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
 foreach (var column in CurrentTable.Columns) {  
		string propertyName = column.OrmPropertyName;

            
            #line default
            #line hidden
            this.Write("\t/// <summary>\r\n\t/// ");
            
            #line 78 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PropertyComment(column)));
            
            #line default
            #line hidden
            this.Write("\r\n\t/// 【");
            
            #line 79 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.OrmColumnTypeString));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 79 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.EngineTypeStringFull));
            
            #line default
            #line hidden
            this.Write("】\r\n\t/// </summary>\r\n\tpublic ");
            
            #line 81 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.DotNetTypeString));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 81 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 82 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t#endregion // 所有列\r\n\r\n\t#region 实体映射\r\n\t\r\n\t/// <summary>\r\n\t/// 将IDataReader映射成实体对象\r" +
                    "\n\t/// </summary>\r\n\t/// <param name = \"reader\">只进结果集流</param>\r\n\t/// <return>实体对象<" +
                    "/return>\r\n\tpublic ");
            
            #line 92 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write(" MapRow(IDataReader reader)\r\n\t{\r\n\t\treturn MapDataReader(reader);\r\n\t}\r\n\t\r\n\t/// <su" +
                    "mmary>\r\n\t/// 将IDataReader映射成实体对象\r\n\t/// </summary>\r\n\t/// <param name = \"reader\">只" +
                    "进结果集流</param>\r\n\t/// <return>实体对象</return>\r\n\tpublic static ");
            
            #line 102 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write(" MapDataReader(IDataReader reader)\r\n\t{\r\n\t    ");
            
            #line 104 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write(" ret = new ");
            
            #line 104 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write("();\r\n");
            
            #line 105 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
 foreach (var column in CurrentTable.Columns) {
		string propertyName = column.OrmPropertyName;

            
            #line default
            #line hidden
            this.Write("\t\tret.");
            
            #line 108 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write(" = reader.");
            
            #line 108 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.OrmReaderMethodName));
            
            #line default
            #line hidden
            this.Write("(\"");
            
            #line 108 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.ColumnName));
            
            #line default
            #line hidden
            this.Write("\");\r\n");
            
            #line 109 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
		if (column.IsPrimaryKey) {
            
            #line default
            #line hidden
            this.Write("\t\tret.Original");
            
            #line 110 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write(" = ret.");
            
            #line 110 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 111 "D:\TinyFx\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableEOT.tt"
		}
	} 
            
            #line default
            #line hidden
            this.Write("\t    return ret;\r\n\t}\r\n\t\r\n\t#endregion\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
