// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 15.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TinyFxVSIX.Commands.OrmGen.Templates.MySqlClient
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using TinyFx.Data.MySqlClient;
    using TinyFx.Data.Schema;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class MySqlViewMOT : MySqlTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("/// <summary>\r\n/// ");
            
            #line 9 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassComment(CurrentView)));
            
            #line default
            #line hidden
            this.Write("\r\n/// 【视图 ");
            
            #line 10 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CurrentView.ViewName));
            
            #line default
            #line hidden
            this.Write(" 的操作类】\r\n/// </summary>\r\npublic class ");
            
            #line 12 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MOName));
            
            #line default
            #line hidden
            this.Write(" : MySqlViewMO<");
            
            #line 12 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write(">\r\n{\r\n    public override string ViewName => \"");
            
            #line 14 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CurrentView.SqlViewName));
            
            #line default
            #line hidden
            this.Write("\"; \r\n\r\n");
            
            #line 16 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
	/**************************** 构造函数 ************************************/ 
            
            #line default
            #line hidden
            this.Write("\t#region Constructors\r\n\t/// <summary>\r\n\t/// 构造函数\r\n\t/// </summary>\r\n\t/// <param na" +
                    "me = \"database\">数据来源</param>\r\n\tpublic ");
            
            #line 22 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MOName));
            
            #line default
            #line hidden
            this.Write("(MySqlDatabase database) : base(database) { }\r\n\r\n\t/// <summary>\r\n\t/// 构造函数\r\n\t/// " +
                    "</summary>\r\n\t/// <param name = \"connectionStringName\">配置文件.config中定义的连接字符串名称</pa" +
                    "ram>\r\n\tpublic ");
            
            #line 28 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MOName));
            
            #line default
            #line hidden
            this.Write(@"(string connectionStringName = null) : base(connectionStringName) { }

    /// <summary>
    /// 构造函数
    /// </summary>
    /// <param name=""connectionString"">数据库连接字符串，如server=192.168.1.1;database=testdb;uid=root;pwd=root</param>
    /// <param name=""commandTimeout"">CommandTimeout时间</param>
    public ");
            
            #line 35 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MOName));
            
            #line default
            #line hidden
            this.Write("(string connectionString, int commandTimeout) : base(connectionString, commandTim" +
                    "eout) { }\r\n\t#endregion // Constructors\r\n\r\n");
            
            #line 38 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
	/**************************** 查询 ************************************/ 
            
            #line default
            #line hidden
            this.Write("\t#region Get\r\n\r\n");
            
            #line 41 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
	foreach(var column in CurrentView.Columns) { 
			string propertyName = column.OrmPropertyName;
			string parameterName = column.OrmParamName;

            
            #line default
            #line hidden
            this.Write("\t#region GetBy");
            
            #line 45 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("\r\n\t\r\n\t/// <summary>\r\n\t/// 按 ");
            
            #line 48 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.ColumnName));
            
            #line default
            #line hidden
            this.Write("（字段） 查询\r\n\t/// </summary>\r\n\t/// ");
            
            #line 50 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ParamComment(column)));
            
            #line default
            #line hidden
            this.Write("\r\n\t/// <return>实体对象集合</return>\r\n\tpublic List<");
            
            #line 52 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write("> GetBy");
            
            #line 52 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 52 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmMethodParamsLink(column)));
            
            #line default
            #line hidden
            this.Write(")\r\n\t{\r\n\t\treturn GetBy");
            
            #line 54 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 54 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameterName));
            
            #line default
            #line hidden
            this.Write(", 0, string.Empty, null);\r\n\t}\r\n\t\r\n\t/// <summary>\r\n\t/// 按 ");
            
            #line 58 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.ColumnName));
            
            #line default
            #line hidden
            this.Write("（字段） 查询\r\n\t/// </summary>\r\n\t/// ");
            
            #line 60 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ParamComment(column)));
            
            #line default
            #line hidden
            this.Write("\r\n\t/// <param name=\"tm_\">事务管理对象</param>\r\n\t/// <return>实体对象集合</return>\r\n\tpublic Li" +
                    "st<");
            
            #line 63 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write("> GetBy");
            
            #line 63 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 63 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmMethodParamsLink(column)));
            
            #line default
            #line hidden
            this.Write(", TransactionManager tm_)\r\n\t{\r\n\t\treturn GetBy");
            
            #line 65 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 65 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameterName));
            
            #line default
            #line hidden
            this.Write(", 0, string.Empty, tm_);\r\n\t}\r\n\t\r\n\t/// <summary>\r\n\t/// 按 ");
            
            #line 69 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.ColumnName));
            
            #line default
            #line hidden
            this.Write("（字段） 查询\r\n\t/// </summary>\r\n\t/// ");
            
            #line 71 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ParamComment(column)));
            
            #line default
            #line hidden
            this.Write("\r\n\t/// <param name = \"top_\">获取行数</param>\r\n\t/// <return>实体对象集合</return>\r\n\tpublic L" +
                    "ist<");
            
            #line 74 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write("> GetBy");
            
            #line 74 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 74 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmMethodParamsLink(column)));
            
            #line default
            #line hidden
            this.Write(", int top_)\r\n\t{\r\n\t\treturn GetBy");
            
            #line 76 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 76 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameterName));
            
            #line default
            #line hidden
            this.Write(", top_, string.Empty, null);\r\n\t}\r\n\t\r\n\t/// <summary>\r\n\t/// 按 ");
            
            #line 80 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.ColumnName));
            
            #line default
            #line hidden
            this.Write("（字段） 查询\r\n\t/// </summary>\r\n\t/// ");
            
            #line 82 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ParamComment(column)));
            
            #line default
            #line hidden
            this.Write("\r\n\t/// <param name = \"top_\">获取行数</param>\r\n\t/// <param name=\"tm_\">事务管理对象</param>\r\n" +
                    "\t/// <return>实体对象集合</return>\r\n\tpublic List<");
            
            #line 86 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write("> GetBy");
            
            #line 86 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 86 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmMethodParamsLink(column)));
            
            #line default
            #line hidden
            this.Write(", int top_, TransactionManager tm_)\r\n\t{\r\n\t\treturn GetBy");
            
            #line 88 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 88 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameterName));
            
            #line default
            #line hidden
            this.Write(", top_, string.Empty, tm_);\r\n\t}\r\n\t\r\n\t/// <summary>\r\n\t/// 按 ");
            
            #line 92 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.ColumnName));
            
            #line default
            #line hidden
            this.Write("（字段） 查询\r\n\t/// </summary>\r\n\t/// ");
            
            #line 94 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ParamComment(column)));
            
            #line default
            #line hidden
            this.Write("\r\n\t/// <param name = \"sort_\">排序表达式</param>\r\n\t/// <return>实体对象集合</return>\r\n\tpublic" +
                    " List<");
            
            #line 97 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write("> GetBy");
            
            #line 97 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 97 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmMethodParamsLink(column)));
            
            #line default
            #line hidden
            this.Write(", string sort_)\r\n\t{\r\n\t\treturn GetBy");
            
            #line 99 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 99 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameterName));
            
            #line default
            #line hidden
            this.Write(", 0, sort_, null);\r\n\t}\r\n\t\r\n\t/// <summary>\r\n\t/// 按 ");
            
            #line 103 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.ColumnName));
            
            #line default
            #line hidden
            this.Write("（字段） 查询\r\n\t/// </summary>\r\n\t/// ");
            
            #line 105 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ParamComment(column)));
            
            #line default
            #line hidden
            this.Write("\r\n\t/// <param name = \"sort_\">排序表达式</param>\r\n\t/// <param name=\"tm_\">事务管理对象</param>" +
                    "\r\n\t/// <return>实体对象集合</return>\r\n\tpublic List<");
            
            #line 109 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write("> GetBy");
            
            #line 109 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 109 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmMethodParamsLink(column)));
            
            #line default
            #line hidden
            this.Write(", string sort_, TransactionManager tm_)\r\n\t{\r\n\t\treturn GetBy");
            
            #line 111 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 111 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameterName));
            
            #line default
            #line hidden
            this.Write(", 0, sort_, tm_);\r\n\t}\r\n\t\r\n\t/// <summary>\r\n\t/// 按 ");
            
            #line 115 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.ColumnName));
            
            #line default
            #line hidden
            this.Write("（字段） 查询\r\n\t/// </summary>\r\n\t/// ");
            
            #line 117 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ParamComment(column)));
            
            #line default
            #line hidden
            this.Write("\r\n\t/// <param name = \"top_\">获取行数</param>\r\n\t/// <param name = \"sort_\">排序表达式</param" +
                    ">\r\n\t/// <param name=\"tm_\">事务管理对象</param>\r\n\t/// <return>实体对象集合</return>\r\n\tpublic " +
                    "List<");
            
            #line 122 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write("> GetBy");
            
            #line 122 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 122 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmMethodParamsLink(column)));
            
            #line default
            #line hidden
            this.Write(", int top_, string sort_, TransactionManager tm_)\r\n\t{\r\n\t\tvar sql_ = BuildSelectSQ" +
                    "L(\"");
            
            #line 124 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmSqlWhereLink(column)));
            
            #line default
            #line hidden
            this.Write("\", top_, sort_);\r\n\t\tvar parameter_ = Database.CreateInParameter(\"");
            
            #line 125 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.SqlParamName));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 125 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.OrmParamValueToDbCode));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 125 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(((MySqlColumnSchema)column).DbTypeString));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\treturn Database.ExecSqlList(sql_, new MySqlParameter[] { parameter_ }, tm_," +
                    " ");
            
            #line 126 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write(".MapDataReader);\r\n\t}\r\n\t#endregion // GetBy");
            
            #line 128 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 130 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlViewMOT.tt"
	} 
            
            #line default
            #line hidden
            this.Write("\r\n\t#endregion // Get\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
