// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 15.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TinyFxVSIX.Commands.OrmGen.Templates.MySqlClient
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using TinyFx.Data.MySqlClient;
    using TinyFx.Data.Schema;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class MySqlTableMOT : MySqlTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("/// <summary>\r\n/// ");
            
            #line 9 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassComment(CurrentTable)));
            
            #line default
            #line hidden
            this.Write("\r\n/// 【表 ");
            
            #line 10 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CurrentTable.TableName));
            
            #line default
            #line hidden
            this.Write(" 的操作类】\r\n/// </summary>\r\npublic class ");
            
            #line 12 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MOName));
            
            #line default
            #line hidden
            this.Write(" : MySqlTableMO<");
            
            #line 12 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write(">\r\n{\r\n    public override string TableName => \"");
            
            #line 14 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CurrentTable.SqlTableName));
            
            #line default
            #line hidden
            this.Write("\"; \r\n\r\n");
            
            #line 16 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
	/**************************** 构造函数 ************************************/ 
            
            #line default
            #line hidden
            this.Write("\t#region Constructors\r\n\t/// <summary>\r\n\t/// 构造函数\r\n\t/// </summary>\r\n\t/// <param na" +
                    "me = \"database\">数据来源</param>\r\n\tpublic ");
            
            #line 22 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MOName));
            
            #line default
            #line hidden
            this.Write("(MySqlDatabase database) : base(database) { }\r\n\r\n\t/// <summary>\r\n\t/// 构造函数\r\n\t/// " +
                    "</summary>\r\n\t/// <param name = \"connectionStringName\">配置文件.config中定义的连接字符串名称</pa" +
                    "ram>\r\n\tpublic ");
            
            #line 28 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MOName));
            
            #line default
            #line hidden
            this.Write(@"(string connectionStringName = null) : base(connectionStringName) { }

    /// <summary>
    /// 构造函数
    /// </summary>
    /// <param name=""connectionString"">数据库连接字符串，如server=192.168.1.1;database=testdb;uid=root;pwd=root</param>
    /// <param name=""commandTimeout"">CommandTimeout时间</param>
    public ");
            
            #line 35 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MOName));
            
            #line default
            #line hidden
            this.Write("(string connectionString, int commandTimeout) : base(connectionString, commandTim" +
                    "eout) { }\r\n\t#endregion // Constructors\r\n\r\n");
            
            #line 38 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
	/**************************** 新增 ************************************/ 
            
            #line default
            #line hidden
            this.Write("    #region  Add\r\n\t/// <summary>\r\n\t/// 插入数据\r\n\t/// </summary>\r\n\t/// <param name = " +
                    "\"item\">要插入的实体对象</param>\r\n\t/// <param name=\"tm\">事务管理对象</param>\r\n\t/// <return>受影响的" +
                    "行数</return>\r\n\tpublic override int Add(");
            
            #line 46 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write(" item, TransactionManager tm = null)\r\n\t{\r\n\t\tconst string sql = @\"INSERT INTO ");
            
            #line 48 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CurrentTable.SqlTableName));
            
            #line default
            #line hidden
            this.Write(" (");
            
            #line 48 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmSqlFieldsLink(CurrentTable, ColumnSelectMode.NoAutoIncrement)));
            
            #line default
            #line hidden
            this.Write(") VALUE (");
            
            #line 48 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmSqlParamsLink(CurrentTable, ColumnSelectMode.NoAutoIncrement)));
            
            #line default
            #line hidden
            this.Write(");");
            
            #line 48 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
 if (CurrentTable.HasAutoIncrementColumn){ 
            
            #line default
            #line hidden
            this.Write("SELECT LAST_INSERT_ID();");
            
            #line 48 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\";\r\n\t\tvar paras = new List<MySqlParameter>() \r\n\t\t{\r\n");
            
            #line 51 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
	foreach(var item in CurrentTable.Columns){ if (item.IsAutoIncrement) continue; 
            
            #line default
            #line hidden
            this.Write("\t\t\tDatabase.CreateInParameter(\"");
            
            #line 52 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.SqlParamName));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 52 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.OrmItemValueToDbCode));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 52 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(((MySqlColumnSchema)item).DbTypeString));
            
            #line default
            #line hidden
            this.Write("),\r\n");
            
            #line 53 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
	} 
            
            #line default
            #line hidden
            this.Write("\t\t};\r\n");
            
            #line 55 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
	if (CurrentTable.HasAutoIncrementColumn){ var column = CurrentTable.AutoIncrementColumn; 
            
            #line default
            #line hidden
            this.Write("\t\titem.");
            
            #line 56 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.OrmPropertyName));
            
            #line default
            #line hidden
            this.Write(" = Database.ExecSqlScalar<");
            
            #line 56 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.DotNetTypeString.TrimEnd('?')));
            
            #line default
            #line hidden
            this.Write(">(sql, paras, tm); \r\n");
            
            #line 57 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
	} else { 
            
            #line default
            #line hidden
            this.Write("\t\tDatabase.ExecSqlNonQuery(sql, paras, tm); \r\n");
            
            #line 59 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
	} 
            
            #line default
            #line hidden
            this.Write("        return 1;\r\n\t}\r\n    \r\n    #endregion // Add\r\n    \r\n");
            
            #line 65 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
	/**************************** 删除 ************************************/ 
            
            #line default
            #line hidden
            this.Write("\t#region  Remove\r\n");
            
            #line 67 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
	if (CurrentTable.HasPrimaryKey){ 
            
            #line default
            #line hidden
            this.Write("\t\r\n\t#region RemoveByPK\r\n\t/// <summary>\r\n\t/// 按主键删除\r\n\t/// </summary>\r\n");
            
            #line 73 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
		foreach (var column in CurrentTable.PrimaryKey.Columns) { 
            
            #line default
            #line hidden
            this.Write("\t/// ");
            
            #line 74 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ParamComment(column)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 75 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
		} 
            
            #line default
            #line hidden
            this.Write("\t/// <param name=\"tm_\">事务管理对象</param>\r\n\tpublic int RemoveByPK(");
            
            #line 77 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmMethodParamsLink(CurrentTable.PrimaryKey.Columns)));
            
            #line default
            #line hidden
            this.Write(", TransactionManager tm_ = null)\r\n\t{\r\n\t\tconst string sql_ = @\"DELETE FROM ");
            
            #line 79 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CurrentTable.SqlTableName));
            
            #line default
            #line hidden
            this.Write(" WHERE ");
            
            #line 79 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmSqlWhereLink(CurrentTable.PrimaryKey.Columns)));
            
            #line default
            #line hidden
            this.Write("\";\r\n\t\tvar paras_ = new List<MySqlParameter>() \r\n\t\t{\r\n");
            
            #line 82 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
		foreach(var column in CurrentTable.PrimaryKey.Columns){ 
            
            #line default
            #line hidden
            this.Write("\t\t\tDatabase.CreateInParameter(\"");
            
            #line 83 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.SqlParamName));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 83 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.OrmParamValueToDbCode));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 83 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(((MySqlColumnSchema)column).DbTypeString));
            
            #line default
            #line hidden
            this.Write("),\r\n");
            
            #line 84 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
		} 
            
            #line default
            #line hidden
            this.Write("\t\t};\r\n\t\treturn Database.ExecSqlNonQuery(sql_, paras_, tm_);\r\n\t}\r\n\t\r\n\t/// <summary" +
                    ">\r\n\t/// 删除指定实体对应的记录\r\n\t/// </summary>\r\n\t/// <param name = \"item\">要删除的实体</param>\r\n" +
                    "\t/// <param name=\"tm\">事务管理对象</param>\r\n\t/// <return>受影响的行数</return>\r\n\tpublic int " +
                    "Remove(");
            
            #line 95 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write(" item, TransactionManager tm = null)\r\n\t{\r\n\t\treturn RemoveByPK(");
            
            #line 97 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmItemValueLink(CurrentTable.PrimaryKey.Columns)));
            
            #line default
            #line hidden
            this.Write(", tm);\r\n\t}\r\n\t#endregion // RemoveByPK\r\n");
            
            #line 100 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
	} 
            
            #line default
            #line hidden
            this.Write("\t\r\n\t#region RemoveByXXX\r\n\r\n");
            
            #line 104 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
	foreach(var column in CurrentTable.ColumnsFilter(ColumnSelectMode.NoOnePK)){ 
            
            #line default
            #line hidden
            this.Write("\t#region RemoveBy");
            
            #line 105 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.OrmPropertyName));
            
            #line default
            #line hidden
            this.Write("\r\n\t/// <summary>\r\n\t/// 按字段删除\r\n\t/// </summary>\r\n\t/// ");
            
            #line 109 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ParamComment(column)));
            
            #line default
            #line hidden
            this.Write("\r\n\t/// <param name=\"tm_\">事务管理对象</param>\r\n\tpublic int RemoveBy");
            
            #line 111 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.OrmPropertyName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 111 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmMethodParamsLink(column)));
            
            #line default
            #line hidden
            this.Write(", TransactionManager tm_ = null)\r\n\t{\r\n\t\tstring sql_ = @\"DELETE FROM ");
            
            #line 113 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CurrentTable.SqlTableName));
            
            #line default
            #line hidden
            this.Write(" WHERE ");
            
            #line 113 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmSqlWhereContent(column)));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\tvar paras_ = new List<MySqlParameter>();\r\n\t\t");
            
            #line 115 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmSqlWhereIF(column)));
            
            #line default
            #line hidden
            this.Write("paras_.Add(Database.CreateInParameter(\"");
            
            #line 115 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.SqlParamName));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 115 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.OrmParamValue));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 115 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(((MySqlColumnSchema)column).DbTypeString));
            
            #line default
            #line hidden
            this.Write("));\r\n\t\treturn Database.ExecSqlNonQuery(sql_, paras_, tm_);\r\n\t}\r\n\t#endregion // Re" +
                    "moveBy");
            
            #line 118 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.OrmPropertyName));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 120 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
	} 
            
            #line default
            #line hidden
            this.Write("\t#endregion // RemoveByXXX\r\n\r\n\t#region RemoveByFKOrUnique\r\n\r\n");
            
            #line 125 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
	foreach(var columns in GetMutilFieldsInUniqueAndFK()){ 
            
            #line default
            #line hidden
            this.Write("\t#region RemoveBy");
            
            #line 126 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmPropertyAndLink(columns)));
            
            #line default
            #line hidden
            this.Write("\r\n\t/// <summary>\r\n\t/// 按字段删除\r\n\t/// </summary>\r\n");
            
            #line 130 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
		foreach(var column in columns){ 
            
            #line default
            #line hidden
            this.Write("\t/// ");
            
            #line 131 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ParamComment(column)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 132 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
		} 
            
            #line default
            #line hidden
            this.Write("\t/// <param name=\"tm_\">事务管理对象</param>\r\n\tpublic int RemoveBy");
            
            #line 134 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmPropertyAndLink(columns)));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 134 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmMethodParamsLink(columns)));
            
            #line default
            #line hidden
            this.Write(", TransactionManager tm_ = null)\r\n\t{\r\n\t\tconst string sql_ = @\"DELETE FROM ");
            
            #line 136 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CurrentTable.SqlTableName));
            
            #line default
            #line hidden
            this.Write(" WHERE ");
            
            #line 136 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmSqlWhereLink(columns)));
            
            #line default
            #line hidden
            this.Write("\";\r\n\t\tvar paras_ = new List<MySqlParameter>() \r\n\t\t{\r\n");
            
            #line 139 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
		foreach(var column in columns){ 
            
            #line default
            #line hidden
            this.Write("\t\t\tDatabase.CreateInParameter(\"");
            
            #line 140 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.SqlParamName));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 140 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.OrmParamValueToDbCode));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 140 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(((MySqlColumnSchema)column).DbTypeString));
            
            #line default
            #line hidden
            this.Write("),\r\n");
            
            #line 141 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
		} 
            
            #line default
            #line hidden
            this.Write("\t\t};\r\n\t\treturn Database.ExecSqlNonQuery(sql_, paras_, tm_);\r\n\t}\r\n\t#endregion // R" +
                    "emoveBy");
            
            #line 145 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmPropertyAndLink(columns)));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 147 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
	} 
            
            #line default
            #line hidden
            this.Write("\t#endregion // RemoveByFKOrUnique\r\n\r\n\t#endregion //Remove\r\n\r\n");
            
            #line 152 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
	/**************************** 修改 ************************************/ 
            
            #line default
            #line hidden
            this.Write("\t#region Put\r\n\r\n");
            
            #line 155 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
	if (CurrentTable.HasPrimaryKey) { 
            
            #line default
            #line hidden
            this.Write("\t#region PutItem\r\n\t/// <summary>\r\n\t/// 更新实体到数据库\r\n\t/// </summary>\r\n\t/// <param nam" +
                    "e = \"item\">要更新的实体对象</param>\r\n\t/// <param name=\"tm\">事务管理对象</param>\r\n\t/// <return>" +
                    "受影响的行数</return>\r\n\tpublic int Put(");
            
            #line 163 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write(" item, TransactionManager tm = null)\r\n\t{\r\n\t\tconst string sql = @\"UPDATE ");
            
            #line 165 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CurrentTable.SqlTableName));
            
            #line default
            #line hidden
            this.Write(" SET ");
            
            #line 165 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmSqlSetLink(CurrentTable, ColumnSelectMode.CanInsertAndUpdate)));
            
            #line default
            #line hidden
            this.Write(" WHERE ");
            
            #line 165 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmSqlWhereLink(CurrentTable.PrimaryKey.Columns, true)));
            
            #line default
            #line hidden
            this.Write("\";\r\n\t\tvar paras = new List<MySqlParameter>() \r\n\t\t{\r\n");
            
            #line 168 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
		foreach(var column in  CurrentTable.ColumnsFilter(ColumnSelectMode.CanInsertAndUpdate)) { 
            
            #line default
            #line hidden
            this.Write("\t\t\tDatabase.CreateInParameter(\"");
            
            #line 169 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.SqlParamName));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 169 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.OrmItemValueToDbCode));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 169 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(((MySqlColumnSchema)column).DbTypeString));
            
            #line default
            #line hidden
            this.Write("),\r\n");
            
            #line 170 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
		} 
            
            #line default
            #line hidden
            
            #line 171 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
		foreach(var column in  CurrentTable.PrimaryKey.Columns) { 
            
            #line default
            #line hidden
            this.Write("\t\t\tDatabase.CreateInParameter(\"");
            
            #line 172 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.SqlParamName));
            
            #line default
            #line hidden
            this.Write("_Original\", item.HasOriginal ? item.Original");
            
            #line 172 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.OrmPropertyName));
            
            #line default
            #line hidden
            this.Write(" : item.");
            
            #line 172 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.OrmPropertyName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 172 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(((MySqlColumnSchema)column).DbTypeString));
            
            #line default
            #line hidden
            this.Write("),\r\n");
            
            #line 173 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
		} 
            
            #line default
            #line hidden
            this.Write(@"		};
		return Database.ExecSqlNonQuery(sql, paras, tm);
	}
	
	/// <summary>
	/// 更新实体集合到数据库
	/// </summary>
	/// <param name = ""items"">要更新的实体对象集合</param>
	/// <param name=""tm"">事务管理对象</param>
	/// <return>受影响的行数</return>
	public int Put(IEnumerable<");
            
            #line 184 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write("> items, TransactionManager tm = null)\r\n\t{\r\n\t\tint ret = 0;\r\n\t\tforeach (var item i" +
                    "n items)\r\n\t\t{\r\n\t        ret += Put(item, tm);\r\n\t\t}\r\n\t\treturn ret;\r\n\t}\r\n\t#endregi" +
                    "on // PutItem\r\n\r\n\t#region PutByPK\r\n\r\n\t/// <summary>\r\n\t/// 按主键更新指定列数据\r\n\t/// </sum" +
                    "mary>\r\n");
            
            #line 200 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
			foreach(var colPK in CurrentTable.PrimaryKey.Columns){ 
            
            #line default
            #line hidden
            this.Write("\t/// ");
            
            #line 201 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ParamComment(colPK)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 202 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
			} 
            
            #line default
            #line hidden
            this.Write("\t/// <param name = \"set_\">更新的列数据</param>\r\n\t/// <param name=\"values_\">参数值</param>\r" +
                    "\n\t/// <return>受影响的行数</return>\r\n\tpublic int PutByPK(");
            
            #line 206 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmMethodParamsLink(CurrentTable.PrimaryKey.Columns)));
            
            #line default
            #line hidden
            this.Write(", string set_, params object[] values_)\r\n\t{\r\n\t\treturn Put(set_, \"");
            
            #line 208 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmSqlWhereLink(CurrentTable.PrimaryKey.Columns)));
            
            #line default
            #line hidden
            this.Write("\", ConcatValues(values_, ");
            
            #line 208 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmMethodParamsValueLink(CurrentTable.PrimaryKey.Columns)));
            
            #line default
            #line hidden
            this.Write("));\r\n\t}\r\n\t/// <summary>\r\n\t/// 按主键更新指定列数据\r\n\t/// </summary>\r\n");
            
            #line 213 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
			foreach(var colPK in CurrentTable.PrimaryKey.Columns){ 
            
            #line default
            #line hidden
            this.Write("\t/// ");
            
            #line 214 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ParamComment(colPK)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 215 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
			} 
            
            #line default
            #line hidden
            this.Write("\t/// <param name = \"set_\">更新的列数据</param>\r\n\t/// <param name=\"tm_\">事务管理对象</param>\r\n" +
                    "\t/// <param name=\"values_\">参数值</param>\r\n\t/// <return>受影响的行数</return>\r\n\tpublic in" +
                    "t PutByPK(");
            
            #line 220 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmMethodParamsLink(CurrentTable.PrimaryKey.Columns)));
            
            #line default
            #line hidden
            this.Write(", string set_, TransactionManager tm_, params object[] values_)\r\n\t{\r\n\t\treturn Put" +
                    "(set_, \"");
            
            #line 222 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmSqlWhereLink(CurrentTable.PrimaryKey.Columns)));
            
            #line default
            #line hidden
            this.Write("\", tm_, ConcatValues(values_, ");
            
            #line 222 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmMethodParamsValueLink(CurrentTable.PrimaryKey.Columns)));
            
            #line default
            #line hidden
            this.Write("));\r\n\t}\r\n\t/// <summary>\r\n\t/// 按主键更新指定列数据\r\n\t/// </summary>\r\n");
            
            #line 227 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
			foreach(var colPK in CurrentTable.PrimaryKey.Columns){ 
            
            #line default
            #line hidden
            this.Write("\t/// ");
            
            #line 228 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ParamComment(colPK)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 229 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
			} 
            
            #line default
            #line hidden
            this.Write("\t/// <param name = \"set_\">更新的列数据</param>\r\n\t/// <param name=\"paras_\">参数值</param>\r\n" +
                    "\t/// <param name=\"tm_\">事务管理对象</param>\r\n\t/// <return>受影响的行数</return>\r\n\tpublic int" +
                    " PutByPK(");
            
            #line 234 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmMethodParamsLink(CurrentTable.PrimaryKey.Columns)));
            
            #line default
            #line hidden
            this.Write(", string set_, IEnumerable<MySqlParameter> paras_, TransactionManager tm_ = null)" +
                    "\r\n\t{\r\n\t\tvar newParas_ = new List<MySqlParameter>() {\r\n");
            
            #line 237 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
		foreach(var column in CurrentTable.PrimaryKey.Columns){ 
            
            #line default
            #line hidden
            this.Write("\t\t\tDatabase.CreateInParameter(\"");
            
            #line 238 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.SqlParamName));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 238 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.OrmParamValueToDbCode));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 238 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(((MySqlColumnSchema)column).DbTypeString));
            
            #line default
            #line hidden
            this.Write("),\r\n");
            
            #line 239 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
		} 
            
            #line default
            #line hidden
            this.Write("        };\r\n\t\treturn Put(set_, \"");
            
            #line 241 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmSqlWhereLink(CurrentTable.PrimaryKey.Columns)));
            
            #line default
            #line hidden
            this.Write("\", ConcatParameters(paras_, newParas_), tm_);\r\n\t}\r\n\t#endregion // PutByPK\r\n");
            
            #line 244 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
	} 
            
            #line default
            #line hidden
            this.Write("\t\r\n\t#region PutXXX\r\n\r\n");
            
            #line 248 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
	foreach(var column in CurrentTable.Columns) { 
		if (column.IsAutoIncrement) continue; 
		if (column.IsSinglePKColumn) continue;

            
            #line default
            #line hidden
            this.Write("\t#region Put");
            
            #line 252 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.OrmPropertyName));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 253 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
		if (CurrentTable.HasPrimaryKey && !column.IsPrimaryKey) { 
            
            #line default
            #line hidden
            this.Write("\t/// <summary>\r\n\t/// 按主键更新列数据\r\n\t/// </summary>\r\n");
            
            #line 257 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
			foreach(var colPK in CurrentTable.PrimaryKey.Columns){ 
            
            #line default
            #line hidden
            this.Write("\t/// ");
            
            #line 258 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ParamComment(colPK)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 259 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
			} 
            
            #line default
            #line hidden
            this.Write("\t/// ");
            
            #line 260 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ParamComment(column)));
            
            #line default
            #line hidden
            this.Write("\r\n\t/// <param name=\"tm_\">事务管理对象</param>\r\n\t/// <return>受影响的行数</return>\r\n\tpublic in" +
                    "t Put");
            
            #line 263 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.OrmPropertyName));
            
            #line default
            #line hidden
            this.Write("ByPK(");
            
            #line 263 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmMethodParamsLink(CurrentTable.PrimaryKey.Columns)));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 263 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmMethodParamsLink(column)));
            
            #line default
            #line hidden
            this.Write(", TransactionManager tm_ = null)\r\n\t{\r\n\t\tconst string sql_ = @\"UPDATE ");
            
            #line 265 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CurrentTable.SqlTableName));
            
            #line default
            #line hidden
            this.Write(" SET ");
            
            #line 265 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmSqlSetLink(column)));
            
            #line default
            #line hidden
            this.Write("  WHERE ");
            
            #line 265 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmSqlWhereLink(CurrentTable.PrimaryKey.Columns)));
            
            #line default
            #line hidden
            this.Write("\";\r\n\t\tvar paras_ = new List<MySqlParameter>() \r\n\t\t{\r\n\t\t\tDatabase.CreateInParamete" +
                    "r(\"");
            
            #line 268 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.SqlParamName));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 268 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.OrmParamValueToDbCode));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 268 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(((MySqlColumnSchema)column).DbTypeString));
            
            #line default
            #line hidden
            this.Write("),\r\n");
            
            #line 269 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
			foreach(var colPK in  CurrentTable.PrimaryKey.Columns) { 
            
            #line default
            #line hidden
            this.Write("\t\t\tDatabase.CreateInParameter(\"");
            
            #line 270 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(colPK.SqlParamName));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 270 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(colPK.OrmParamValueToDbCode));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 270 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(((MySqlColumnSchema)colPK).DbTypeString));
            
            #line default
            #line hidden
            this.Write("),\r\n");
            
            #line 271 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
			} 
            
            #line default
            #line hidden
            this.Write("\t\t};\r\n\t\treturn Database.ExecSqlNonQuery(sql_, paras_, tm_);\r\n\t}\r\n");
            
            #line 275 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
		} 
            
            #line default
            #line hidden
            this.Write(" \r\n\t/// <summary>\r\n\t/// 更新一列数据\r\n\t/// </summary>\r\n\t/// ");
            
            #line 279 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ParamComment(column)));
            
            #line default
            #line hidden
            this.Write("\r\n\t/// <param name=\"tm_\">事务管理对象</param>\r\n\t/// <return>受影响的行数</return>\r\n\tpublic in" +
                    "t Put");
            
            #line 282 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.OrmPropertyName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 282 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmMethodParamsLink(column)));
            
            #line default
            #line hidden
            this.Write(", TransactionManager tm_ = null)\r\n\t{\r\n\t\tconst string sql_ = @\"UPDATE ");
            
            #line 284 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CurrentTable.SqlTableName));
            
            #line default
            #line hidden
            this.Write(" SET ");
            
            #line 284 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmSqlSetLink(column)));
            
            #line default
            #line hidden
            this.Write("\";\r\n\t\tvar parameter_ = Database.CreateInParameter(\"");
            
            #line 285 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.SqlParamName));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 285 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.OrmParamValueToDbCode));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 285 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(((MySqlColumnSchema)column).DbTypeString));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\treturn Database.ExecSqlNonQuery(sql_, new MySqlParameter[] { parameter_ }, " +
                    "tm_);\r\n\t}\r\n\t#endregion // Put");
            
            #line 288 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.OrmPropertyName));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 290 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
	} 
            
            #line default
            #line hidden
            this.Write("\t#endregion // PutXXX\r\n\t\r\n\t#endregion // Put\r\n   \r\n");
            
            #line 295 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
	/**************************** 修改或新增 ************************************/ 
            
            #line default
            #line hidden
            
            #line 296 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
	if (CurrentTable.HasPrimaryKey) { 
            
            #line default
            #line hidden
            this.Write("\t#region Set\r\n\t\r\n\t/// <summary>\r\n\t/// 插入或者更新数据\r\n\t/// </summary>\r\n\t/// <param name" +
                    " = \"item\">要更新的实体对象</param>\r\n\t/// <param name=\"tm\">事务管理对象</param>\r\n\t/// <return>t" +
                    "rue:插入操作；false:更新操作</return>\r\n\tpublic bool Set(");
            
            #line 305 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write(" item, TransactionManager tm = null)\r\n\t{\r\n\t\tbool ret = true;\r\n\t\tif(GetByPK(");
            
            #line 308 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmItemValueLink(CurrentTable.PrimaryKey.Columns)));
            
            #line default
            #line hidden
            this.Write(") == null)\r\n\t\t{\r\n\t\t\tAdd(item, tm);\r\n\t\t}\r\n\t\telse\r\n\t\t{\r\n\t\t\tPut(item, tm);\r\n\t\t\tret =" +
                    " false;\r\n\t\t}\r\n\t\treturn ret;\r\n\t}\r\n\t\r\n\t#endregion // Set\r\n");
            
            #line 321 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
	} 
            
            #line default
            #line hidden
            this.Write("\t\r\n");
            
            #line 323 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
	/**************************** 查询 ************************************/ 
            
            #line default
            #line hidden
            this.Write("\t#region Get\r\n\r\n");
            
            #line 326 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
	if (CurrentTable.HasPrimaryKey) { 
            
            #line default
            #line hidden
            this.Write("\t#region GetByPK\r\n\t/// <summary>\r\n\t/// 按 PK（主键） 查询\r\n\t/// </summary>\r\n");
            
            #line 331 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
		foreach (var column in CurrentTable.PrimaryKey.Columns) { 
            
            #line default
            #line hidden
            this.Write("\t/// ");
            
            #line 332 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ParamComment(column)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 333 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
		} 
            
            #line default
            #line hidden
            this.Write("\t/// <param name=\"tm_\">事务管理对象</param>\r\n\t/// <return></return>\r\n\tpublic ");
            
            #line 336 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write(" GetByPK(");
            
            #line 336 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmMethodParamsLink(CurrentTable.PrimaryKey.Columns)));
            
            #line default
            #line hidden
            this.Write(", TransactionManager tm_ = null)\r\n\t{\r\n\t\tvar sql_ = BuildSelectSQL(\"");
            
            #line 338 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmSqlWhereLink(CurrentTable.PrimaryKey.Columns)));
            
            #line default
            #line hidden
            this.Write("\", 0, null);\r\n\t\tvar paras_ = new List<MySqlParameter>() \r\n\t\t{\r\n");
            
            #line 341 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
		foreach(var column in CurrentTable.PrimaryKey.Columns){ 
            
            #line default
            #line hidden
            this.Write("\t\t\tDatabase.CreateInParameter(\"");
            
            #line 342 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.SqlParamName));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 342 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.OrmParamValueToDbCode));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 342 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(((MySqlColumnSchema)column).DbTypeString));
            
            #line default
            #line hidden
            this.Write("),\r\n");
            
            #line 343 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
		} 
            
            #line default
            #line hidden
            this.Write("\t\t};\r\n\t\treturn Database.ExecSqlSingle(sql_, paras_, tm_, ");
            
            #line 345 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write(".MapDataReader);\r\n\t}\r\n\t#endregion // GetByPK\r\n");
            
            #line 348 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
	} 
            
            #line default
            #line hidden
            this.Write("\t\r\n");
            
            #line 350 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
	if (CurrentTable.HasUniqueIndex) {
            
            #line default
            #line hidden
            this.Write("\t#region GetByUnique\r\n");
            
            #line 352 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
		foreach (var index in CurrentTable.Indexes) {
			if (!index.IsUnique || index.IsPrimaryKey) continue;

            
            #line default
            #line hidden
            this.Write("\t/// <summary>\r\n\t/// 按【唯一索引】查询\r\n\t/// </summary>\r\n");
            
            #line 358 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
			foreach(var column in index.Columns){ 
            
            #line default
            #line hidden
            this.Write("\t/// ");
            
            #line 359 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ParamComment(column)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 360 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
			} 
            
            #line default
            #line hidden
            this.Write("\t/// <param name=\"tm_\">事务管理对象</param>\r\n\tpublic ");
            
            #line 362 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write(" GetBy");
            
            #line 362 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmPropertyAndLink(index.Columns)));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 362 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmMethodParamsLink(index.Columns)));
            
            #line default
            #line hidden
            this.Write(", TransactionManager tm_ = null)\r\n\t{\r\n\t\tvar sql_ = BuildSelectSQL(\"");
            
            #line 364 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmSqlWhereLink(index.Columns)));
            
            #line default
            #line hidden
            this.Write("\", 0, null);\r\n\t\tvar paras_ = new List<MySqlParameter>() \r\n\t\t{\r\n");
            
            #line 367 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
			foreach(var column in index.Columns){ 
            
            #line default
            #line hidden
            this.Write("\t\t\tDatabase.CreateInParameter(\"");
            
            #line 368 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.SqlParamName));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 368 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.OrmParamValueToDbCode));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 368 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(((MySqlColumnSchema)column).DbTypeString));
            
            #line default
            #line hidden
            this.Write("),\r\n");
            
            #line 369 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
			} 
            
            #line default
            #line hidden
            this.Write("\t\t};\r\n\t\treturn Database.ExecSqlSingle(sql_, paras_, tm_, ");
            
            #line 371 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write(".MapDataReader);\r\n\t}\r\n\r\n");
            
            #line 374 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
		} 
            
            #line default
            #line hidden
            this.Write("\t#endregion // GetByUnique\r\n");
            
            #line 376 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
	} 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 378 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
 if (CurrentTable.HasForeignKey) {
            
            #line default
            #line hidden
            this.Write("\t#region GetByFK\r\n\r\n");
            
            #line 381 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
		foreach (var fk in CurrentTable.ForeignKeys) { if (fk.Columns.Count == 1) continue; 
            
            #line default
            #line hidden
            this.Write("\t/// <summary>\r\n\t/// 按【外键】查询\r\n\t/// </summary>\r\n");
            
            #line 385 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
			foreach(var column in fk.Columns){ 
            
            #line default
            #line hidden
            this.Write("\t/// ");
            
            #line 386 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ParamComment(column)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 387 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
			} 
            
            #line default
            #line hidden
            this.Write("\t/// <param name=\"tm_\">事务管理对象</param>\r\n\tpublic List<");
            
            #line 389 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write("> GetBy");
            
            #line 389 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmPropertyAndLink(fk.Columns)));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 389 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmMethodParamsLink(fk.Columns)));
            
            #line default
            #line hidden
            this.Write(", TransactionManager tm_ = null)\r\n\t{\r\n\t\tvar sql_ = BuildSelectSQL(\"");
            
            #line 391 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmSqlWhereLink(fk.Columns)));
            
            #line default
            #line hidden
            this.Write("\", 0, null);\r\n\t\tvar paras_ = new List<MySqlParameter>() \r\n\t\t{\r\n");
            
            #line 394 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
			foreach(var column in fk.Columns){ 
            
            #line default
            #line hidden
            this.Write("\t\t\tDatabase.CreateInParameter(\"");
            
            #line 395 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.SqlParamName));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 395 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.OrmParamValueToDbCode));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 395 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(((MySqlColumnSchema)column).DbTypeString));
            
            #line default
            #line hidden
            this.Write("),\r\n");
            
            #line 396 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
			} 
            
            #line default
            #line hidden
            this.Write("\t\t};\r\n\t\treturn Database.ExecSqlList(sql_, paras_, tm_, ");
            
            #line 398 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write(".MapDataReader);\r\n\t}\r\n");
            
            #line 400 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
		} 
            
            #line default
            #line hidden
            this.Write("\t#endregion // GetByFK\r\n");
            
            #line 402 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
	} 
            
            #line default
            #line hidden
            this.Write("\r\n\t#region GetByXXX\r\n\r\n");
            
            #line 406 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
	foreach(var column in CurrentTable.Columns) { 
			if (column.IsSinglePKColumn || column.IsSingleUniqueColumn) continue;
			string propertyName = column.OrmPropertyName;
			string parameterName = column.OrmParamName;

            
            #line default
            #line hidden
            this.Write("\t#region GetBy");
            
            #line 411 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("\r\n\t\r\n\t/// <summary>\r\n\t/// 按 ");
            
            #line 414 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.ColumnName));
            
            #line default
            #line hidden
            this.Write("（字段） 查询\r\n\t/// </summary>\r\n\t/// ");
            
            #line 416 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ParamComment(column)));
            
            #line default
            #line hidden
            this.Write("\r\n\t/// <return>实体对象集合</return>\r\n\tpublic List<");
            
            #line 418 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write("> GetBy");
            
            #line 418 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 418 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmMethodParamsLink(column)));
            
            #line default
            #line hidden
            this.Write(")\r\n\t{\r\n\t\treturn GetBy");
            
            #line 420 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 420 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameterName));
            
            #line default
            #line hidden
            this.Write(", 0, string.Empty, null);\r\n\t}\r\n\t\r\n\t/// <summary>\r\n\t/// 按 ");
            
            #line 424 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.ColumnName));
            
            #line default
            #line hidden
            this.Write("（字段） 查询\r\n\t/// </summary>\r\n\t/// ");
            
            #line 426 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ParamComment(column)));
            
            #line default
            #line hidden
            this.Write("\r\n\t/// <param name=\"tm_\">事务管理对象</param>\r\n\t/// <return>实体对象集合</return>\r\n\tpublic Li" +
                    "st<");
            
            #line 429 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write("> GetBy");
            
            #line 429 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 429 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmMethodParamsLink(column)));
            
            #line default
            #line hidden
            this.Write(", TransactionManager tm_)\r\n\t{\r\n\t\treturn GetBy");
            
            #line 431 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 431 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameterName));
            
            #line default
            #line hidden
            this.Write(", 0, string.Empty, tm_);\r\n\t}\r\n\t\r\n\t/// <summary>\r\n\t/// 按 ");
            
            #line 435 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.ColumnName));
            
            #line default
            #line hidden
            this.Write("（字段） 查询\r\n\t/// </summary>\r\n\t/// ");
            
            #line 437 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ParamComment(column)));
            
            #line default
            #line hidden
            this.Write("\r\n\t/// <param name = \"top_\">获取行数</param>\r\n\t/// <return>实体对象集合</return>\r\n\tpublic L" +
                    "ist<");
            
            #line 440 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write("> GetBy");
            
            #line 440 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 440 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmMethodParamsLink(column)));
            
            #line default
            #line hidden
            this.Write(", int top_)\r\n\t{\r\n\t\treturn GetBy");
            
            #line 442 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 442 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameterName));
            
            #line default
            #line hidden
            this.Write(", top_, string.Empty, null);\r\n\t}\r\n\t\r\n\t/// <summary>\r\n\t/// 按 ");
            
            #line 446 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.ColumnName));
            
            #line default
            #line hidden
            this.Write("（字段） 查询\r\n\t/// </summary>\r\n\t/// ");
            
            #line 448 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ParamComment(column)));
            
            #line default
            #line hidden
            this.Write("\r\n\t/// <param name = \"top_\">获取行数</param>\r\n\t/// <param name=\"tm_\">事务管理对象</param>\r\n" +
                    "\t/// <return>实体对象集合</return>\r\n\tpublic List<");
            
            #line 452 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write("> GetBy");
            
            #line 452 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 452 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmMethodParamsLink(column)));
            
            #line default
            #line hidden
            this.Write(", int top_, TransactionManager tm_)\r\n\t{\r\n\t\treturn GetBy");
            
            #line 454 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 454 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameterName));
            
            #line default
            #line hidden
            this.Write(", top_, string.Empty, tm_);\r\n\t}\r\n\t\r\n\t/// <summary>\r\n\t/// 按 ");
            
            #line 458 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.ColumnName));
            
            #line default
            #line hidden
            this.Write("（字段） 查询\r\n\t/// </summary>\r\n\t/// ");
            
            #line 460 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ParamComment(column)));
            
            #line default
            #line hidden
            this.Write("\r\n\t/// <param name = \"sort_\">排序表达式</param>\r\n\t/// <return>实体对象集合</return>\r\n\tpublic" +
                    " List<");
            
            #line 463 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write("> GetBy");
            
            #line 463 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 463 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmMethodParamsLink(column)));
            
            #line default
            #line hidden
            this.Write(", string sort_)\r\n\t{\r\n\t\treturn GetBy");
            
            #line 465 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 465 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameterName));
            
            #line default
            #line hidden
            this.Write(", 0, sort_, null);\r\n\t}\r\n\t\r\n\t/// <summary>\r\n\t/// 按 ");
            
            #line 469 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.ColumnName));
            
            #line default
            #line hidden
            this.Write("（字段） 查询\r\n\t/// </summary>\r\n\t/// ");
            
            #line 471 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ParamComment(column)));
            
            #line default
            #line hidden
            this.Write("\r\n\t/// <param name = \"sort_\">排序表达式</param>\r\n\t/// <param name=\"tm_\">事务管理对象</param>" +
                    "\r\n\t/// <return>实体对象集合</return>\r\n\tpublic List<");
            
            #line 475 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write("> GetBy");
            
            #line 475 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 475 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmMethodParamsLink(column)));
            
            #line default
            #line hidden
            this.Write(", string sort_, TransactionManager tm_)\r\n\t{\r\n\t\treturn GetBy");
            
            #line 477 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 477 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameterName));
            
            #line default
            #line hidden
            this.Write(", 0, sort_, tm_);\r\n\t}\r\n\t\r\n\t/// <summary>\r\n\t/// 按 ");
            
            #line 481 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.ColumnName));
            
            #line default
            #line hidden
            this.Write("（字段） 查询\r\n\t/// </summary>\r\n\t/// ");
            
            #line 483 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ParamComment(column)));
            
            #line default
            #line hidden
            this.Write("\r\n\t/// <param name = \"top_\">获取行数</param>\r\n\t/// <param name = \"sort_\">排序表达式</param" +
                    ">\r\n\t/// <param name=\"tm_\">事务管理对象</param>\r\n\t/// <return>实体对象集合</return>\r\n\tpublic " +
                    "List<");
            
            #line 488 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write("> GetBy");
            
            #line 488 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 488 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmMethodParamsLink(column)));
            
            #line default
            #line hidden
            this.Write(", int top_, string sort_, TransactionManager tm_)\r\n\t{\r\n\t\tvar sql_ = BuildSelectSQ" +
                    "L(");
            
            #line 490 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmSqlWhereContent(column, true)));
            
            #line default
            #line hidden
            this.Write(", top_, sort_);\r\n\t\tvar paras_ = new List<MySqlParameter>();\r\n\t\t");
            
            #line 492 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmSqlWhereIF(column)));
            
            #line default
            #line hidden
            this.Write("paras_.Add(Database.CreateInParameter(\"");
            
            #line 492 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.SqlParamName));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 492 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.OrmParamValue));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 492 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(((MySqlColumnSchema)column).DbTypeString));
            
            #line default
            #line hidden
            this.Write("));\r\n\t\treturn Database.ExecSqlList(sql_, paras_, tm_, ");
            
            #line 493 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EOName));
            
            #line default
            #line hidden
            this.Write(".MapDataReader);\r\n\t}\r\n\t#endregion // GetBy");
            
            #line 495 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 497 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlTableMOT.tt"
	} 
            
            #line default
            #line hidden
            this.Write("\t#endregion // GetByXXX\r\n\r\n\t#endregion // Get\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
