// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 15.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TinyFxVSIX.Commands.OrmGen.Templates.MySqlClient
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using TinyFx.Data.MySqlClient;
    using TinyFx.Data.Schema;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class MySqlProcMOT : MySqlTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("/// <summary>\r\n/// ");
            
            #line 9 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassComment(CurrentProc)));
            
            #line default
            #line hidden
            this.Write("\r\n/// 【存储过程 ");
            
            #line 10 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CurrentProc.ProcName));
            
            #line default
            #line hidden
            this.Write(" 的操作类】\r\n/// </summary>\r\npublic class ");
            
            #line 12 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MOName));
            
            #line default
            #line hidden
            this.Write(" : MySqlProcMO\r\n{\r\n    public override string ProcName => \"");
            
            #line 14 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CurrentProc.SqlProcName));
            
            #line default
            #line hidden
            this.Write("\";\r\n\r\n");
            
            #line 16 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
	/**************************** 构造函数 ************************************/ 
            
            #line default
            #line hidden
            this.Write("\t#region Constructors\r\n\t/// <summary>\r\n\t/// 构造函数\r\n\t/// </summary>\r\n\t/// <param na" +
                    "me = \"database\">数据来源</param>\r\n\tpublic ");
            
            #line 22 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MOName));
            
            #line default
            #line hidden
            this.Write("(MySqlDatabase database) : base(database) { }\r\n\r\n\t/// <summary>\r\n\t/// 构造函数\r\n\t/// " +
                    "</summary>\r\n\t/// <param name = \"connectionStringName\">配置文件.config中定义的连接字符串名称</pa" +
                    "ram>\r\n\tpublic ");
            
            #line 28 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MOName));
            
            #line default
            #line hidden
            this.Write(@"(string connectionStringName = null) : base(connectionStringName) { }

    /// <summary>
    /// 构造函数
    /// </summary>
    /// <param name=""connectionString"">数据库连接字符串，如server=192.168.1.1;database=testdb;uid=root;pwd=root</param>
    /// <param name=""commandTimeout"">CommandTimeout时间</param>
    public ");
            
            #line 35 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MOName));
            
            #line default
            #line hidden
            this.Write("(string connectionString, int commandTimeout) : base(connectionString, commandTim" +
                    "eout) { }\r\n\t#endregion // Constructors\r\n\r\n\t// 获取ProcDao\r\n\tprivate MySqlProcDao G" +
                    "etProcDao(");
            
            #line 39 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmMethodParamsLink(CurrentProc.InputParameters)));
            
            #line default
            #line hidden
            this.Write("TransactionManager tm = null)\r\n\t{\r\n\t\tvar ret = new MySqlProcDao(ProcName, Databas" +
                    "e);\r\n");
            
            #line 42 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
 foreach(var para in CurrentProc.InputParameters) { 
            
            #line default
            #line hidden
            this.Write("\t\tret.AddInParameter(\"");
            
            #line 43 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(para.SqlParamName));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 43 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(para.OrmParamValueToDbCode));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 43 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(((MySqlParameterSchema)para).DbTypeString));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 44 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
 } 
            
            #line default
            #line hidden
            
            #line 45 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
 foreach(var para in CurrentProc.OutputParameters) { 
            
            #line default
            #line hidden
            this.Write("\t\tret.AddOutParameter(\"");
            
            #line 46 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(para.SqlParamName));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 46 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(((MySqlParameterSchema)para).DbTypeString));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 47 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        return ret;\r\n\t}\r\n\r\n\t/// <summary>\r\n\t/// 获取单行数据\r\n\t/// </summary>\r\n");
            
            #line 54 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
 foreach(var para in CurrentProc.InputParameters) { 
            
            #line default
            #line hidden
            this.Write("\t/// ");
            
            #line 55 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ParamComment(para)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 56 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t/// <param name=\"tm\">事务对象</param>\r\n\t/// <returns></returns>\r\n\tpublic DataRow Exe" +
                    "cSingle(");
            
            #line 59 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmMethodParamsLink(CurrentProc.InputParameters)));
            
            #line default
            #line hidden
            this.Write("TransactionManager tm = null)\r\n\t{\r\n\t\tusing (var dao = GetProcDao(");
            
            #line 61 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmMethodParamsValueLink(CurrentProc.InputParameters, false)));
            
            #line default
            #line hidden
            this.Write("))\r\n\t\t{\r\n\t\t\treturn dao.ExecSingle(tm);\r\n\t\t}\r\n\t}\r\n\t/// <summary>\r\n\t/// 获取DataTable" +
                    "数据\r\n\t/// </summary>\r\n");
            
            #line 69 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
 foreach(var para in CurrentProc.InputParameters) { 
            
            #line default
            #line hidden
            this.Write("\t/// ");
            
            #line 70 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ParamComment(para)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 71 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t/// <param name=\"tm\">事务对象</param>\r\n\t/// <returns></returns>\r\n\tpublic DataTable E" +
                    "xecTable(");
            
            #line 74 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmMethodParamsLink(CurrentProc.InputParameters)));
            
            #line default
            #line hidden
            this.Write("TransactionManager tm = null)\r\n\t{\r\n\t\tusing (var dao = GetProcDao(");
            
            #line 76 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmMethodParamsValueLink(CurrentProc.InputParameters, false)));
            
            #line default
            #line hidden
            this.Write("))\r\n\t\t{\r\n\t\t\treturn dao.ExecTable(tm);\r\n\t\t}\r\n\t}\r\n\r\n\t/// <summary>\r\n\t/// 获取首行首列值\r\n\t" +
                    "/// </summary>\r\n\t/// <typeparam name=\"T\">目标类型</typeparam>\r\n");
            
            #line 86 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
 foreach(var para in CurrentProc.InputParameters) { 
            
            #line default
            #line hidden
            this.Write("\t/// ");
            
            #line 87 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ParamComment(para)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 88 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t/// <param name=\"tm\">事务对象</param>\r\n\t/// <returns></returns>\r\n\tpublic T ExecScala" +
                    "r<T>(");
            
            #line 91 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmMethodParamsLink(CurrentProc.InputParameters)));
            
            #line default
            #line hidden
            this.Write("TransactionManager tm = null)\r\n\t{\r\n\t    return ExecSingle(");
            
            #line 93 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmMethodParamsValueLink(CurrentProc.InputParameters, true)));
            
            #line default
            #line hidden
            this.Write("tm)[0].ConvertTo<T>();\r\n\t}\r\n\r\n\t/// <summary>\r\n\t/// 获取执行存储过程返回的所有数据\r\n\t/// </summar" +
                    "y>\r\n");
            
            #line 99 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
 foreach(var para in CurrentProc.InputParameters) { 
            
            #line default
            #line hidden
            this.Write("\t/// ");
            
            #line 100 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ParamComment(para)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 101 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t/// <param name=\"tm\">事务对象</param>\r\n\t/// <returns></returns>\r\n\tpublic ResultData " +
                    "Execute(");
            
            #line 104 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmMethodParamsLink(CurrentProc.InputParameters)));
            
            #line default
            #line hidden
            this.Write("TransactionManager tm = null)\r\n\t{\r\n\t    ResultData ret = null;\r\n\t    using (var d" +
                    "ao = GetProcDao(");
            
            #line 107 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOrmMethodParamsValueLink(CurrentProc.InputParameters, false)));
            
            #line default
            #line hidden
            this.Write(@"))
	    {
	        var reader = dao.ExecReader(tm);
	        if (reader.FieldCount == 0) return null;
	        ret = new ResultData();
	        do
	        {
	            var table = reader.ToTable(false);
	            ret.Results.Add(table);
	        }
	        while (reader.NextResult());
");
            
            #line 118 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
 foreach(var para in  CurrentProc.OutputParameters) { 
            
            #line default
            #line hidden
            this.Write("\t        ret.");
            
            #line 119 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(para.OrmPropertyName));
            
            #line default
            #line hidden
            this.Write(" = dao.GetParameterValue<");
            
            #line 119 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(para.DotNetTypeString));
            
            #line default
            #line hidden
            this.Write(">(\"");
            
            #line 119 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(para.SqlParamName));
            
            #line default
            #line hidden
            this.Write("\");\r\n");
            
            #line 120 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t    }\r\n\t    return ret;\r\n\t}\r\n\r\n\t/// <summary>\r\n\t/// 存储过程返回的数据对象\r\n\t/// </summary>" +
                    "\r\n\tpublic class ResultData\r\n\t{\r\n");
            
            #line 130 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
 if (CurrentProc.HasOutputParameter) { 
            
            #line default
            #line hidden
            this.Write("\t\t#region OutputParameters\r\n");
            
            #line 132 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
		foreach(var param in CurrentProc.OutputParameters) { 
            
            #line default
            #line hidden
            this.Write("\t\r\n\t\t/// <summary>\r\n\t\t/// 输出参数\r\n\t\t/// 【");
            
            #line 135 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(param.ParameterName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 135 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(param.EngineTypeStringFull));
            
            #line default
            #line hidden
            this.Write("】\r\n\t\t/// </summary>\r\n\t\tpublic ");
            
            #line 137 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(param.DotNetTypeString));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 137 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(param.OrmPropertyName));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 138 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
		} 
            
            #line default
            #line hidden
            this.Write("\t\r\n\t\t#endregion // OutputParameters\r\n");
            
            #line 140 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\MySqlClient\MySqlProcMOT.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"
	    /// <summary>
	    /// 存储过程返回的结果集集合
	    /// </summary>
	    public List<DataTable> Results = new List<DataTable>();
		
		/// <summary>
		/// 是否有结果集
		/// </summary>
	    public bool HasResult => Results.Count > 0;

	    /// <summary>
	    /// 获取存储过程返回的第一个DataTable结果集
	    /// </summary>
	    public DataTable FirstResult => HasResult ? Results[0] : null;
	}
}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
