// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 15.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TinyFxVSIX.Commands.OrmGen.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\OrmTemplateBase.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class OrmTemplateBase : OrmTemplateBaseBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            return this.GenerationEnvironment.ToString();
        }
        
        #line 6 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\OrmTemplateBase.tt"
 
// 导入版权信息 **********************************************************************************************************
public void ImportCopyright()
{

        
        #line default
        #line hidden
        
        #line 10 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\OrmTemplateBase.tt"
this.Write("/******************************************************\r\n * 此代码由代码生成器工具自动生成，请不要修改" +
        "\r\n * 代码生成器核心库版本号：2.0 by JiangHui 2016-06-20\r\n * 创建时间：");

        
        #line default
        #line hidden
        
        #line 14 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\OrmTemplateBase.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss")));

        
        #line default
        #line hidden
        
        #line 14 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\OrmTemplateBase.tt"
this.Write("\r\n ******************************************************/\r\n");

        
        #line default
        #line hidden
        
        #line 16 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\OrmTemplateBase.tt"

}
// 导入引用 ******************************************************************************************************************
public void ImportUsings(List<string> namespaces)
{

        
        #line default
        #line hidden
        
        #line 21 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\OrmTemplateBase.tt"
this.Write(@"using System;
using System.Data;
using System.Data.Common;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Security.Permissions;
using System.Xml;
using System.Xml.Serialization;
using System.Text;
using TinyFx;
using TinyFx.Data;
using TinyFx.Data.ORM;
using MySql.Data;
using MySql.Data.MySqlClient;
");

        
        #line default
        #line hidden
        
        #line 38 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\OrmTemplateBase.tt"

	foreach(var item in namespaces)
    {

        
        #line default
        #line hidden
        
        #line 41 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\OrmTemplateBase.tt"
this.Write("using ");

        
        #line default
        #line hidden
        
        #line 42 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\OrmTemplateBase.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(item));

        
        #line default
        #line hidden
        
        #line 42 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\OrmTemplateBase.tt"
this.Write(";\r\n");

        
        #line default
        #line hidden
        
        #line 43 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\OrmTemplateBase.tt"

    }
}
// 内容添加Namespace *********************************************************************************************************
public void AddNamespace1(string content, string namespaceName)
{

        
        #line default
        #line hidden
        
        #line 49 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\OrmTemplateBase.tt"
this.Write("namespace ");

        
        #line default
        #line hidden
        
        #line 50 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\OrmTemplateBase.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(namespaceName));

        
        #line default
        #line hidden
        
        #line 50 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\OrmTemplateBase.tt"
this.Write("\r\n{\r\n");

        
        #line default
        #line hidden
        
        #line 52 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\OrmTemplateBase.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(content));

        
        #line default
        #line hidden
        
        #line 52 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\OrmTemplateBase.tt"
this.Write("\r\n}\r\n");

        
        #line default
        #line hidden
        
        #line 54 "D:\TinyFx\develop\src\TinyFxVSIX.Commands.OrmGen\Templates\OrmTemplateBase.tt"

}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class OrmTemplateBaseBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
